-- Schéma de base pour l'application de gestion commerciale

ALTER SESSION SET CURRENT_SCHEMA = APP_USER;

CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code VARCHAR2(30) UNIQUE NOT NULL,
    customer_name VARCHAR2(200) NOT NULL,
    customer_type VARCHAR2(30) DEFAULT 'CUSTOMER',
    email VARCHAR2(200),
    phone VARCHAR2(50),
    status VARCHAR2(20) DEFAULT 'ACTIVE',
    created_at DATE DEFAULT SYSDATE
);

CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR2(30) UNIQUE NOT NULL,
    product_name VARCHAR2(200) NOT NULL,
    unit_price NUMBER(12,2) NOT NULL,
    currency_code VARCHAR2(3) DEFAULT 'EUR',
    status VARCHAR2(20) DEFAULT 'ACTIVE',
    created_at DATE DEFAULT SYSDATE
);

CREATE TABLE sales_orders (
    sales_order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR2(30) UNIQUE NOT NULL,
    customer_id NUMBER NOT NULL REFERENCES customers(customer_id),
    order_date DATE DEFAULT SYSDATE,
    order_status VARCHAR2(20) DEFAULT 'DRAFT',
    total_amount NUMBER(12,2) DEFAULT 0
);

CREATE TABLE sales_order_lines (
    sales_order_line_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sales_order_id NUMBER NOT NULL REFERENCES sales_orders(sales_order_id),
    product_id NUMBER NOT NULL REFERENCES products(product_id),
    quantity NUMBER(10,2) NOT NULL,
    unit_price NUMBER(12,2) NOT NULL,
    line_amount NUMBER(12,2) NOT NULL
);

CREATE TABLE invoices (
    invoice_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number VARCHAR2(30) UNIQUE NOT NULL,
    sales_order_id NUMBER REFERENCES sales_orders(sales_order_id),
    customer_id NUMBER NOT NULL REFERENCES customers(customer_id),
    invoice_date DATE DEFAULT SYSDATE,
    invoice_status VARCHAR2(20) DEFAULT 'OPEN',
    total_amount NUMBER(12,2) DEFAULT 0
);

CREATE TABLE payments (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id NUMBER NOT NULL REFERENCES invoices(invoice_id),
    payment_date DATE DEFAULT SYSDATE,
    payment_amount NUMBER(12,2) NOT NULL,
    payment_method VARCHAR2(30) DEFAULT 'TRANSFER',
    payment_status VARCHAR2(20) DEFAULT 'REGISTERED'
);

CREATE TABLE audit_log (
    audit_log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_name VARCHAR2(100) NOT NULL,
    action_name VARCHAR2(100) NOT NULL,
    actor_name VARCHAR2(100),
    action_details CLOB,
    created_at DATE DEFAULT SYSDATE
);
