-- Script d'initialisation Oracle complet pour l'application de gestion commerciale
-- À exécuter en tant que SYS ou un utilisateur disposant des droits nécessaires.

ALTER SESSION SET CURRENT_SCHEMA = SYS;

PROMPT Creating application user
DECLARE
    l_user_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_user_exists FROM all_users WHERE username = UPPER('APP_USER');
    IF l_user_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER APP_USER IDENTIFIED BY "ChangeMe_AppUser_123!" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
    END IF;
END;
/

PROMPT Granting basic privileges
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, CREATE TYPE TO APP_USER;
GRANT UNLIMITED TABLESPACE TO APP_USER;

PROMPT Creating roles
DECLARE
    l_role_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_role_exists FROM dba_roles WHERE role = 'APP_ADMIN';
    IF l_role_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE ROLE APP_ADMIN';
    END IF;

    SELECT COUNT(*) INTO l_role_exists FROM dba_roles WHERE role = 'SALES_USER';
    IF l_role_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE ROLE SALES_USER';
    END IF;

    SELECT COUNT(*) INTO l_role_exists FROM dba_roles WHERE role = 'FINANCE_USER';
    IF l_role_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE ROLE FINANCE_USER';
    END IF;
END;
/

GRANT APP_ADMIN, SALES_USER, FINANCE_USER TO APP_USER;
GRANT CREATE SESSION TO APP_ADMIN, SALES_USER, FINANCE_USER;

PROMPT Creating audit table for security and traceability
DECLARE
    l_table_exists NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO l_table_exists
    FROM all_tables
    WHERE owner = 'APP_USER'
      AND table_name = 'AUDIT_LOG';

    IF l_table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE APP_USER.audit_log (
                audit_log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                module_name VARCHAR2(100) NOT NULL,
                action_name VARCHAR2(100) NOT NULL,
                actor_name VARCHAR2(100),
                action_details CLOB,
                created_at DATE DEFAULT SYSDATE
            )';
    END IF;
END;
/

PROMPT Creating secured views
DECLARE
    l_customer_table_exists NUMBER;
    l_order_table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO l_customer_table_exists FROM all_tables WHERE owner = 'APP_USER' AND table_name = 'CUSTOMERS';
    SELECT COUNT(*) INTO l_order_table_exists FROM all_tables WHERE owner = 'APP_USER' AND table_name = 'SALES_ORDERS';

    IF l_customer_table_exists = 1 THEN
        EXECUTE IMMEDIATE 'CREATE OR REPLACE VIEW APP_USER.v_customers AS SELECT customer_id, customer_code, customer_name, customer_type, email, phone, status FROM APP_USER.customers';
        EXECUTE IMMEDIATE 'GRANT SELECT ON APP_USER.v_customers TO APP_ADMIN, SALES_USER, FINANCE_USER';
    END IF;

    IF l_order_table_exists = 1 THEN
        EXECUTE IMMEDIATE 'CREATE OR REPLACE VIEW APP_USER.v_sales_orders AS SELECT sales_order_id, order_number, customer_id, order_date, order_status, total_amount FROM APP_USER.sales_orders';
        EXECUTE IMMEDIATE 'GRANT SELECT ON APP_USER.v_sales_orders TO APP_ADMIN, SALES_USER, FINANCE_USER';
    END IF;
END;
/

PROMPT Initialization complete
