-- Phase 3 hardening - authentification API et autorisation par role
-- A executer avec APP_USER avant sql/010_phase3_ords_rest.sql

ALTER SESSION SET CURRENT_SCHEMA = APP_USER;

BEGIN
    EXECUTE IMMEDIATE q'[
CREATE TABLE app_api_clients (
    client_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_code VARCHAR2(40) NOT NULL,
    client_name VARCHAR2(120) NOT NULL,
    role_code VARCHAR2(30) NOT NULL,
    api_key_hash VARCHAR2(64) NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    expires_at DATE,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    updated_at DATE,
    CONSTRAINT uq_app_api_clients_code UNIQUE (client_code),
    CONSTRAINT uq_app_api_clients_hash UNIQUE (api_key_hash),
    CONSTRAINT ck_app_api_clients_role CHECK (role_code IN ('APP_ADMIN', 'SALES_USER', 'FINANCE_USER', 'REPORT_USER')),
    CONSTRAINT ck_app_api_clients_status CHECK (status IN ('ACTIVE', 'REVOKED'))
)
]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

CREATE OR REPLACE PACKAGE pkg_security AS
    FUNCTION normalize_key(p_api_key IN VARCHAR2) RETURN VARCHAR2;
    FUNCTION has_role_access(p_role_code IN VARCHAR2, p_allowed_roles IN VARCHAR2) RETURN NUMBER;
    FUNCTION get_access_status(p_api_key IN VARCHAR2, p_allowed_roles IN VARCHAR2) RETURN NUMBER;
    FUNCTION require_access(p_api_key IN VARCHAR2, p_allowed_roles IN VARCHAR2) RETURN NUMBER;

    PROCEDURE upsert_api_client(
        p_client_code IN VARCHAR2,
        p_client_name IN VARCHAR2,
        p_role_code IN VARCHAR2,
        p_api_key IN VARCHAR2,
        p_expires_at IN DATE DEFAULT NULL
    );

    PROCEDURE revoke_api_client(p_client_code IN VARCHAR2);
END pkg_security;
/

CREATE OR REPLACE PACKAGE BODY pkg_security AS
    FUNCTION normalize_key(p_api_key IN VARCHAR2) RETURN VARCHAR2 IS
    BEGIN
        RETURN TRIM(NVL(p_api_key, ''));
    END normalize_key;

    FUNCTION has_role_access(p_role_code IN VARCHAR2, p_allowed_roles IN VARCHAR2) RETURN NUMBER IS
        l_allowed_roles VARCHAR2(4000);
        l_role_token VARCHAR2(200);
    BEGIN
        l_allowed_roles := ',' || REPLACE(UPPER(NVL(p_allowed_roles, '')), ' ', '') || ',';
        l_role_token := ',' || REPLACE(UPPER(TRIM(p_role_code)), ' ', '') || ',';

        IF INSTR(l_allowed_roles, l_role_token) > 0 THEN
            RETURN 1;
        END IF;
        RETURN 0;
    END has_role_access;

    FUNCTION get_access_status(p_api_key IN VARCHAR2, p_allowed_roles IN VARCHAR2) RETURN NUMBER IS
        l_role_code app_api_clients.role_code%TYPE;
        l_key VARCHAR2(512);
    BEGIN
        l_key := normalize_key(p_api_key);

        IF l_key IS NULL OR l_key = '' THEN
            RETURN 401;
        END IF;

        SELECT role_code
          INTO l_role_code
          FROM app_api_clients
         WHERE api_key_hash = STANDARD_HASH(l_key, 'SHA256')
           AND status = 'ACTIVE'
           AND (expires_at IS NULL OR expires_at >= SYSDATE);

        IF has_role_access(l_role_code, p_allowed_roles) = 0 THEN
            RETURN 403;
        END IF;

        RETURN 200;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 401;
    END get_access_status;

    FUNCTION require_access(p_api_key IN VARCHAR2, p_allowed_roles IN VARCHAR2) RETURN NUMBER IS
        l_status NUMBER;
    BEGIN
        l_status := get_access_status(p_api_key, p_allowed_roles);

        IF l_status = 401 THEN
            RAISE_APPLICATION_ERROR(-20041, 'Missing API key');
        END IF;

        IF l_status = 403 THEN
            RAISE_APPLICATION_ERROR(-20043, 'Forbidden for role');
        END IF;

        RETURN 1;
    END require_access;

    PROCEDURE upsert_api_client(
        p_client_code IN VARCHAR2,
        p_client_name IN VARCHAR2,
        p_role_code IN VARCHAR2,
        p_api_key IN VARCHAR2,
        p_expires_at IN DATE DEFAULT NULL
    ) IS
        l_client_code VARCHAR2(40) := UPPER(TRIM(p_client_code));
        l_role_code VARCHAR2(30) := UPPER(TRIM(p_role_code));
        l_key VARCHAR2(512) := normalize_key(p_api_key);
    BEGIN
        IF l_client_code IS NULL OR l_role_code IS NULL OR l_key IS NULL OR l_key = '' THEN
            RAISE_APPLICATION_ERROR(-20044, 'client_code, role_code and api_key are required');
        END IF;

        MERGE INTO app_api_clients tgt
        USING (
            SELECT l_client_code AS client_code,
                   p_client_name AS client_name,
                   l_role_code AS role_code,
                   STANDARD_HASH(l_key, 'SHA256') AS api_key_hash,
                   p_expires_at AS expires_at
              FROM dual
        ) src
           ON (tgt.client_code = src.client_code)
         WHEN MATCHED THEN
              UPDATE SET
                  tgt.client_name = src.client_name,
                  tgt.role_code = src.role_code,
                  tgt.api_key_hash = src.api_key_hash,
                  tgt.status = 'ACTIVE',
                  tgt.expires_at = src.expires_at,
                  tgt.updated_at = SYSDATE
         WHEN NOT MATCHED THEN
              INSERT (client_code, client_name, role_code, api_key_hash, status, expires_at, created_at, updated_at)
              VALUES (src.client_code, src.client_name, src.role_code, src.api_key_hash, 'ACTIVE', src.expires_at, SYSDATE, SYSDATE);
    END upsert_api_client;

    PROCEDURE revoke_api_client(p_client_code IN VARCHAR2) IS
    BEGIN
        UPDATE app_api_clients
           SET status = 'REVOKED',
               updated_at = SYSDATE
         WHERE client_code = UPPER(TRIM(p_client_code));
    END revoke_api_client;
END pkg_security;
/

CREATE OR REPLACE VIEW v_api_clients AS
SELECT client_id,
       client_code,
       client_name,
       role_code,
       status,
       expires_at,
       created_at,
       updated_at
  FROM app_api_clients;
/

BEGIN
    pkg_security.upsert_api_client('GC_ADMIN',   'Gestion Commerciale Admin',   'APP_ADMIN',   'GC_ADMIN_CHANGE_ME_2026!');
    pkg_security.upsert_api_client('GC_SALES',   'Gestion Commerciale Sales',   'SALES_USER',  'GC_SALES_CHANGE_ME_2026!');
    pkg_security.upsert_api_client('GC_FINANCE', 'Gestion Commerciale Finance', 'FINANCE_USER','GC_FINANCE_CHANGE_ME_2026!');
    pkg_security.upsert_api_client('GC_REPORT',  'Gestion Commerciale Report',  'REPORT_USER', 'GC_REPORT_CHANGE_ME_2026!');
    COMMIT;
END;
/

PROMPT Phase 3 security objects created. Change default API keys immediately with pkg_security.upsert_api_client.
